# Generated by Django 2.2 on 2019-09-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190922_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/code.jpg', upload_to='static/blog/images'),
        ),
    ]
