# Generated by Django 2.2 on 2019-09-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20190922_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/code.jpg', null=True, upload_to='post_pics/'),
        ),
    ]
