# Generated by Django 2.2 on 2019-09-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20190922_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='media/code.jpg', null=True, upload_to='post_pics/'),
        ),
    ]
