# Generated by Django 2.2 on 2019-09-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190922_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/339827-PAEAQ1-592.jpg', upload_to='profile_pics'),
        ),
    ]
